languageCode = "en-us"
title = "UPPAAL Documentation"

theme = "hugo-theme-learn"

baseURL = "https://statictest.test.cs.aau.dk/uppaaldoc"
canonifyURLs = "true"

#baseURL = "."
#canonifyURLs = "true"
#uglyURLs="true"
#relativeURLs="true"


# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = ""
  editURL = "https://git.its.aau.dk/UPPAAL/docs.uppaal.org/src/branch/master/content/"

[markup.goldmark.renderer]
unsafe=true