languageCode = "en-us"
title = "UPPAAL Documentation"

theme = "hugo-theme-learn"

#baseURL = "https://uppaalmodelchecker.github.io/docs.uppaal.org/"
#canonifyURLs = "true"

#baseURL = "."
#canonifyURLs = "true"
#uglyURLs="true"
#relativeURLs="true"


# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = ""
  editURL = "https://github.com/UPPAALModelChecker/docs.uppaal.org/blob/master/content/"

[markup.goldmark.renderer]
unsafe=true
